### ISSUE TITLE
icons in android flutter 

### ISSUE THREAD

**Issue by kunacademy1** [hugeicons/hugeicons-flutter#2]
icons work well in the ios version but when run in the Android version the icons change to Chinese simple

**Comment by hirokbanik** [comment]
I have already opened an issue https://github.com/hugeicons/hugeicons-flutter/issues/1

For the time being, you may replace the woff2 with ttf font at %LOCALAPPDATA%\Pub\Cache\hosted\pub.dev\hugeicons-0.0.5\lib\fonts . Also update the pubspec.yaml

**Comment by hugeicons** [comment]
Updated with .ttf font format, please check. Thanks.
