### ISSUE TITLE
No Stoke width Option

### ISSUE THREAD

**Issue by zg0ul** [hugeicons/hugeicons-flutter#5]
It would be nice if we could choose a stroke just like on the website, currently, the only stroke level available in flutter is 1 from my observation.

**Comment by hugeicons** [comment]
Hi there,

This Flutter package use .ttf fonts, which makes it impossible to change the strokeWidth for font icons. However, it is possible to have different preset weights like thin, regular, bold. We don’t have this feature yet, but we’re planning to implement it soon.
